const $=id=>document.getElementById(id);
const ranks=['A','2','3','4','5','6','7','8','9','10','J','Q','K'], suits=['♠','♥','♦','♣'];
const chipVals=[1,5,10,25,50,100]; let selected=25, bankroll=+localStorage.bjBankroll||2000;
let shoe=[], dealer=[], player=[], hidden=true, inRound=false, bets={main:0,between:0,buster:0,poker:0};
function save(){localStorage.bjBankroll=bankroll} function money(n){return '$'+n}
function msg(t){$('message').textContent=t} function haptic(){try{navigator.vibrate?.(20)}catch(e){}}
function buildShoe(){shoe=[]; for(let d=0;d<6;d++) for(const s of suits) for(const r of ranks) shoe.push({r,s}); shuffle(shoe); updateShoe()}
function shuffle(a){for(let i=a.length-1;i>0;i--){let j=Math.floor(Math.random()*(i+1));[a[i],a[j]]=[a[j],a[i]]}}
function updateShoe(){$('shoeCount').textContent=`${shoe.length} cards in shoe`}
function cardVal(c){if(c.r==='A')return 11; if(['K','Q','J'].includes(c.r))return 10; return +c.r}
function total(hand){let t=0,a=0; for(const c of hand){t+=cardVal(c); if(c.r==='A')a++} while(t>21&&a){t-=10;a--} return t}
function isSoft(hand){let t=0,a=0; for(const c of hand){t+=cardVal(c); if(c.r==='A')a++} return a&&t<=21}
function drawCard(c,back=false){let el=document.createElement('div'); el.className='card '+(back?'back':(c.s==='♥'||c.s==='♦'?'red':'')); if(back){el.innerHTML='<div class="mid">♠</div>';return el} el.innerHTML=`<div>${c.r}${c.s}</div><div class="mid">${c.s}</div><div class="bot">${c.r}${c.s}</div>`; return el}
function render(){ $('bankroll').textContent=money(bankroll); ['main','between','buster','poker'].forEach(k=>$(k+'Amt').textContent=money(bets[k])); $('dealerCards').innerHTML=''; dealer.forEach((c,i)=>$('dealerCards').appendChild(drawCard(c,hidden&&i===1))); $('playerCards').innerHTML=''; player.forEach(c=>$('playerCards').appendChild(drawCard(c))); $('playerTotal').textContent=player.length?`(${total(player)})`:''; $('dealerTotal').textContent=dealer.length? hidden?`(${cardVal(dealer[0])})`:`(${total(dealer)})`:''; updateShoe(); save(); }
function placeBet(k){ if(inRound)return; if(bankroll<selected){msg('Not enough bankroll for that chip.');return} bankroll-=selected; bets[k]+=selected; haptic(); render(); }
function clearBets(){ if(inRound)return; let s=Object.values(bets).reduce((a,b)=>a+b,0); bankroll+=s; bets={main:0,between:0,buster:0,poker:0}; render(); msg('Bets cleared.') }
function take(){if(shoe.length<52){showShuffle()} return shoe.pop()}
function showShuffle(){ $('shuffleOverlay').style.display='grid'; buildShoe(); setTimeout(()=>$('shuffleOverlay').style.display='none',800)}
function setActions(on){inRound=on; $('dealBtn').disabled=on; $('hitBtn').disabled=!on; $('standBtn').disabled=!on; $('doubleBtn').disabled=!on||player.length!==2||bankroll<bets.main; $('clearBtn').disabled=on;}
function deal(){ if(!bets.main){msg('Place a main bet first.');return} dealer=[take(),take()]; player=[take(),take()]; hidden=true; setActions(true); render(); settleInstantSidebets(); if(total(player)===21){stand(true)} else msg('Your move: Hit, Stand, or Double.');}
function hit(){player.push(take()); render(); if(total(player)>21)finish('Player busts. Dealer wins.'); else {$('doubleBtn').disabled=true; msg('Hit or stand.')}}
function doubleDown(){ if(player.length!==2||bankroll<bets.main)return; bankroll-=bets.main; bets.main*=2; player.push(take()); render(); if(total(player)>21)finish('Player busts after double.'); else stand();}
function stand(auto=false){ hidden=false; render(); setTimeout(()=>{ while(total(dealer)<17 || (total(dealer)===17&&isSoft(dealer))) dealer.push(take()); render(); settleMain();}, auto?400:200)}
function settleMain(){ let pt=total(player), dt=total(dealer), text=''; if(pt>21) text='Player busts.'; else if(dt>21){let win=bets.main*2; bankroll+=win; text=`Dealer busts. You win ${money(bets.main)}.`; settleBuster(true)} else if(pt>dt){bankroll+=bets.main*2;text=`You win ${money(bets.main)}.`} else if(pt===dt){bankroll+=bets.main;text='Push.'} else text='Dealer wins.'; if(total(player)===21&&player.length===2 && !(total(dealer)===21&&dealer.length===2)){bankroll+=Math.floor(bets.main*2.5)-bets.main*2;text='Blackjack pays 3:2!'} finish(text)}
function finish(text){setActions(false); bets={main:0,between:0,buster:0,poker:0}; hidden=false; render(); msg(text+' Place the next bet.');}
function settleInstantSidebets(){let notes=[]; let up=dealer[0]; if(bets.between){let a=rankNum(player[0]), b=rankNum(player[1]), u=rankNum(up); let lo=Math.min(a,b), hi=Math.max(a,b); if(a===b){bankroll+=bets.between; notes.push('In Between pushes on pair.')} else if(u>lo&&u<hi){let mult=(up.s===player[0].s&&up.s===player[1].s)?20:(u===(lo+hi)/2?10:2); bankroll+=bets.between*(mult+1); notes.push(`In Between hits ${mult}:1.`)} else notes.push('In Between loses.')} if(bets.poker){let mult=pokerPay([player[0],player[1],up]); if(mult){bankroll+=bets.poker*(mult+1); notes.push(`3 Card Poker pays ${mult}:1.`)} else notes.push('3 Card Poker loses.')} render(); if(notes.length) msg(notes.join(' '));}
function settleBuster(didBust){ if(!bets.buster)return; if(!didBust){msg($('message').textContent+' Dealer Buster loses.');return} let n=dealer.length, mult=n>=7?50:n===6?12:n===5?4:n===4?2:1; bankroll+=bets.buster*(mult+1); msg($('message').textContent+` Dealer Buster pays ${mult}:1.`)}
function rankNum(c){return c.r==='A'?14:['K','Q','J'].includes(c.r)?10:+c.r}
function pokerPay(h){let vals=h.map(rankNum).sort((a,b)=>a-b), flush=h.every(c=>c.s===h[0].s), counts={}; vals.forEach(v=>counts[v]=(counts[v]||0)+1); let trips=Object.values(counts).includes(3), pair=Object.values(counts).includes(2); let straight=(vals[2]-vals[0]===2&&new Set(vals).size===3)||(vals.join(',')==='2,3,14'); if(straight&&flush)return 40; if(trips)return 30; if(straight)return 6; if(flush)return 3; if(pair)return 1; return 0}
function newShoe(){showShuffle(); dealer=[]; player=[]; hidden=true; render(); msg('Fresh 6-deck shoe shuffled.')} 
chipVals.forEach(v=>{let c=document.createElement('button'); c.className='chip'; c.textContent='$'+v; c.style.background=v==1?'#1f6f43':v==5?'#b0172a':v==10?'#1c4f9c':v==25?'#202020':v==50?'#6d2c91':'#b8860b'; if(v===selected)c.classList.add('selected'); c.onclick=()=>{selected=v;document.querySelectorAll('.chip').forEach(x=>x.classList.remove('selected'));c.classList.add('selected')}; $('chips').appendChild(c)})
document.querySelectorAll('[data-bet]').forEach(b=>b.onclick=()=>placeBet(b.dataset.bet)); $('mainBetSpot').onclick=()=>placeBet('main'); $('clearBtn').onclick=clearBets; $('dealBtn').onclick=deal; $('hitBtn').onclick=hit; $('standBtn').onclick=()=>stand(); $('doubleBtn').onclick=doubleDown; $('newShoeBtn').onclick=newShoe;
buildShoe(); render(); setActions(false); msg('Place your bets. Tap chip values first, then tap betting circles.');
