const $=id=>document.getElementById(id);
const ranks=['A','2','3','4','5','6','7','8','9','10','J','Q','K'], suits=['♠','♥','♦','♣'];
const chipVals=[1,5,10,25,50,100]; let selected=25, bankroll=+(localStorage.bjBankroll||2000);
let shoe=[], dealer=[], hidden=true, inRound=false, active=0, sideSettled=false;
let bets={main:0,between:0,buster:0,poker:0}; let hands=[]; let ledger=[];
const money=n=>(n<0?'-':'')+'$'+Math.abs(Math.round(n)); const save=()=>localStorage.bjBankroll=bankroll;
function msg(t){$('message').textContent=t} function haptic(ms=18){try{navigator.vibrate?.(ms)}catch(e){}}
function buildShoe(){shoe=[]; for(let d=0;d<6;d++) for(const s of suits) for(const r of ranks) shoe.push({r,s}); shuffle(shoe); updateShoe()}
function shuffle(a){for(let i=a.length-1;i>0;i--){const j=Math.floor(Math.random()*(i+1));[a[i],a[j]]=[a[j],a[i]]}}
function updateShoe(){$('shoeCount').textContent=`${shoe.length} cards in shoe`}
function v(c){if(c.r==='A')return 11;if('KQJ'.includes(c.r))return 10;return +c.r} function tenVal(c){return c.r==='A'?11:('KQJ'.includes(c.r)?10:+c.r)}
function total(h){let t=0,a=0; for(const c of h.cards){t+=v(c); if(c.r==='A')a++} while(t>21&&a){t-=10;a--} return t}
function isSoftArr(cards){let t=0,a=0; for(const c of cards){t+=v(c); if(c.r==='A')a++} return a&&t<=21}
function totalArr(cards){let t=0,a=0; for(const c of cards){t+=v(c); if(c.r==='A')a++} while(t>21&&a){t-=10;a--} return t}
function canSplit(h){return inRound && !h.done && h.cards.length===2 && bankroll>=h.bet && splitRank(h.cards[0])===splitRank(h.cards[1])}
function splitRank(c){return c.r==='A'?'A':(('KQJ'.includes(c.r)||c.r==='10')?'10':c.r)}
function cardEl(c,back=false){let el=document.createElement('div'); el.className='card '+(back?'back':(c.s==='♥'||c.s==='♦'?'red':'')); if(back){el.innerHTML='<div class="mid">♠</div>';return el} el.innerHTML=`<div>${c.r}${c.s}</div><div class="mid">${c.s}</div><div class="bot">${c.r}${c.s}</div>`; return el}
function render(){ $('bankroll').textContent=money(bankroll); ['main','between','buster','poker'].forEach(k=>$(k+'Amt').textContent=money(bets[k]));
 $('dealerCards').innerHTML=''; dealer.forEach((c,i)=>$('dealerCards').appendChild(cardEl(c,hidden&&i===1))); $('dealerTotal').textContent=dealer.length?(hidden?`(${v(dealer[0])})`:`(${totalArr(dealer)})`):'';
 $('handsWrap').innerHTML=''; hands.forEach((h,i)=>{const box=document.createElement('div'); box.className='player-hand '+(i===active&&inRound?'active':''); const stat=h.bust?' BUST':h.done?' DONE':''; box.innerHTML=`<div class="hand-title">Hand ${i+1} · ${money(h.bet)} · ${total(h)}${stat}</div><div class="hand"></div>`; h.cards.forEach(c=>box.querySelector('.hand').appendChild(cardEl(c))); $('handsWrap').appendChild(box)});
 $('mainAmt').textContent=money(bets.main); renderLedger(); updateActions(); updateShoe(); save(); }
function renderLedger(){const el=$('ledger'); if(!ledger.length){el.className='ledger'; el.innerHTML=''; return} el.className='ledger show'; el.innerHTML='<b>Hand result</b><br>'+ledger.map(x=>`<span class="${x.cls}">${x.text}</span>`).join('<br>')}
function placeBet(k){if(inRound)return; if(bankroll<selected){msg('Not enough bankroll for that chip.');return} bankroll-=selected; bets[k]+=selected; ledger=[]; haptic(); render()}
function clearBets(){if(inRound)return; bankroll+=Object.values(bets).reduce((a,b)=>a+b,0); bets={main:0,between:0,buster:0,poker:0}; ledger=[]; render(); msg('Bets cleared.')}
function take(){if(shoe.length<52)showShuffle(); return shoe.pop()} function sleep(ms){return new Promise(r=>setTimeout(r,ms))}
function showShuffle(){ $('shuffleOverlay').style.display='grid'; buildShoe(); setTimeout(()=>$('shuffleOverlay').style.display='none',850)}
function updateActions(){const h=hands[active]; $('dealBtn').disabled=inRound; $('clearBtn').disabled=inRound; $('hitBtn').disabled=!inRound||!h||h.done; $('standBtn').disabled=!inRound||!h||h.done; $('doubleBtn').disabled=!inRound||!h||h.done||h.cards.length!==2||bankroll<h.bet; $('splitBtn').disabled=!h||!canSplit(h)}
async function deal(){if(!bets.main){msg('Place a main bet first.');return} inRound=true; hidden=true; active=0; sideSettled=false; ledger=[]; dealer=[]; hands=[{cards:[],bet:bets.main,done:false,bust:false,blackjack:false,splitAces:false}]; render();
 hands[0].cards.push(take()); render(); await sleep(140); dealer.push(take()); render(); await sleep(140); hands[0].cards.push(take()); render(); await sleep(140); dealer.push(take()); render(); await sleep(140);
 settleSideBetsInstant(); hands[0].blackjack=total(hands[0])===21&&hands[0].cards.length===2; if(hands[0].blackjack){await dealerPlayAndSettle()} else {msg('Your move. Hit, Stand, Double, or Split if available.'); render()}}
function settleSideBetsInstant(){if(sideSettled)return; sideSettled=true; const first=hands[0].cards, up=dealer[0]; const wager=bets.between+bets.poker; if(bets.between){let a=rankNum(first[0]),b=rankNum(first[1]),u=rankNum(up),lo=Math.min(a,b),hi=Math.max(a,b),profit=-bets.between; if(a===b){bankroll+=bets.between; profit=0; ledger.push({cls:'push',text:`In Between: push (${money(profit)})`})} else if(u>lo&&u<hi){let mult=(up.s===first[0].s&&up.s===first[1].s)?20:(u===(lo+hi)/2?10:2); bankroll+=bets.between*(mult+1); profit=bets.between*mult; ledger.push({cls:'pos',text:`In Between: won ${money(profit)} (${mult}:1)`})} else ledger.push({cls:'neg',text:`In Between: lost ${money(bets.between)}`})}
 if(bets.poker){let mult=pokerPay([first[0],first[1],up]); if(mult){bankroll+=bets.poker*(mult+1); ledger.push({cls:'pos',text:`3 Card Poker: won ${money(bets.poker*mult)} (${pokerName([first[0],first[1],up])})`})} else ledger.push({cls:'neg',text:`3 Card Poker: lost ${money(bets.poker)}`})}
 if(wager) msg('Side bets settled. Finish the blackjack hand.'); render()}
async function hit(){const h=hands[active]; h.cards.push(take()); haptic(); render(); await sleep(100); if(total(h)>21){h.bust=true; h.done=true; nextHandOrDealer()} else msg('Hit, Stand, Double, or Split if available.')}
async function stand(){hands[active].done=true; haptic(); nextHandOrDealer()}
async function doubleDown(){const h=hands[active]; if(h.cards.length!==2||bankroll<h.bet)return; bankroll-=h.bet; h.bet*=2; h.cards.push(take()); h.done=true; h.bust=total(h)>21; ledger.push({cls:'push',text:`Hand ${active+1}: doubled to ${money(h.bet)}`}); render(); await sleep(160); nextHandOrDealer()}
async function splitHand(){const h=hands[active]; if(!canSplit(h))return; bankroll-=h.bet; const c2=h.cards.pop(); const newHand={cards:[c2],bet:h.bet,done:false,bust:false,blackjack:false,splitAces:c2.r==='A'}; h.splitAces=h.cards[0].r==='A'; hands.splice(active+1,0,newHand); h.cards.push(take()); newHand.cards.push(take()); ledger.push({cls:'push',text:`Split into Hand ${active+1} and Hand ${active+2} (${money(h.bet)} each)`}); if(h.splitAces){h.done=true; newHand.done=true} render(); await sleep(180); nextHandOrDealer(false)}
async function nextHandOrDealer(advance=true){if(advance){for(let i=active+1;i<hands.length;i++){if(!hands[i].done){active=i; msg(`Playing Hand ${i+1}.`); render(); return}}} else {for(let i=0;i<hands.length;i++){if(!hands[i].done){active=i; msg(`Playing Hand ${i+1}.`); render(); return}}} await dealerPlayAndSettle()}
async function dealerPlayAndSettle(){hidden=false; render(); await sleep(300); const anyLive=hands.some(h=>!h.bust); while(anyLive && (totalArr(dealer)<17 || (totalArr(dealer)===17&&isSoftArr(dealer)))){dealer.push(take()); render(); await sleep(270)} settleAll()}
function settleAll(){const dt=totalArr(dealer), dealerBust=dt>21; let mainProfit=0; hands.forEach((h,i)=>{let profit=-h.bet, cls='neg', label='lost'; const pt=total(h); if(h.blackjack && !(dt===21&&dealer.length===2)){profit=Math.floor(h.bet*1.5); bankroll+=h.bet+profit; label='blackjack paid 3:2'; cls='pos'} else if(h.bust){label='busted'} else if(dealerBust || pt>dt){profit=h.bet; bankroll+=h.bet*2; label='won'; cls='pos'} else if(pt===dt){profit=0; bankroll+=h.bet; label='pushed'; cls='push'} mainProfit+=profit; ledger.push({cls,text:`Main Hand ${i+1}: ${label} ${money(profit)} (${pt} vs dealer ${dealerBust?'bust':dt})`})});
 if(bets.buster){if(dealerBust){const mult=busterMult(dealer.length); const profit=bets.buster*mult; bankroll+=bets.buster*(mult+1); ledger.push({cls:'pos',text:`Dealer Buster: won ${money(profit)} (dealer busted on ${dealer.length} cards, ${mult}:1)`})} else ledger.push({cls:'neg',text:`Dealer Buster: lost ${money(bets.buster)} (dealer did not bust)`})}
 const totalBet=bets.between+bets.poker+bets.buster+hands.reduce((s,h)=>s+h.bet,0); const net=ledger.reduce((s,x)=>{const m=x.text.match(/(?:won|lost|pushed|push|busted|3:2) ([-]?)\$?(\d+)/);return s},0); ledger.push({cls:'push',text:`Total amount wagered/resolved this round: ${money(totalBet)}. Bankroll now ${money(bankroll)}.`});
 msg(dealerBust?'Dealer busts. Round complete.':'Round complete.'); inRound=false; hidden=false; bets={main:0,between:0,buster:0,poker:0}; render()}
function busterMult(n){return n>=7?50:n===6?12:n===5?4:n===4?2:1}
function rankNum(c){return c.r==='A'?14:('KQJ'.includes(c.r)?10:+c.r)}
function pokerPay(h){let vals=h.map(rankNum).sort((a,b)=>a-b), flush=h.every(c=>c.s===h[0].s), counts={}; vals.forEach(v=>counts[v]=(counts[v]||0)+1); let trips=Object.values(counts).includes(3), pair=Object.values(counts).includes(2); let straight=(vals[2]-vals[0]===2&&new Set(vals).size===3)||(vals.join(',')==='2,3,14'); if(straight&&flush)return 40; if(trips)return 30; if(straight)return 6; if(flush)return 3; if(pair)return 1; return 0}
function pokerName(h){let p=pokerPay(h); return p===40?'straight flush':p===30?'three of a kind':p===6?'straight':p===3?'flush':p===1?'pair':'loss'}
function newShoe(){showShuffle(); dealer=[]; hands=[]; hidden=true; ledger=[]; inRound=false; render(); msg('Fresh 6-deck shoe shuffled.')}
chipVals.forEach(v=>{let c=document.createElement('button'); c.className='chip'; c.textContent='$'+v; c.style.background=v==1?'#1f6f43':v==5?'#b0172a':v==10?'#1c4f9c':v==25?'#202020':v==50?'#6d2c91':'#b8860b'; if(v===selected)c.classList.add('selected'); c.onclick=()=>{selected=v;document.querySelectorAll('.chip').forEach(x=>x.classList.remove('selected'));c.classList.add('selected')}; $('chips').appendChild(c)});
document.querySelectorAll('[data-bet]').forEach(b=>b.onclick=()=>placeBet(b.dataset.bet)); $('mainBetSpot').onclick=()=>placeBet('main'); $('clearBtn').onclick=clearBets; $('dealBtn').onclick=deal; $('hitBtn').onclick=hit; $('standBtn').onclick=stand; $('doubleBtn').onclick=doubleDown; $('splitBtn').onclick=splitHand; $('newShoeBtn').onclick=newShoe;
buildShoe(); render(); msg('Place bets. Tap a chip, then tap the betting circles.');
